---
- name: Collect show version
  hosts: cisco

  tasks:
    - name: configure top level configuration
      ios_config:
        lines: logging host 10.1.1.1

    - name: run show run
      ios_command:
        commands: show runn | in logging
      register: output
    
    - debug: var=output  


  